name: OmarianAtman
favicon: null
layout_spectrum: 0.5295265484601259
typography_spectrum: 0.5545360178221017
title: Legacy Of Light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41015549446456134
  lightness: 0.9946369829121977
  saturation: 0.2720134954433888
  rhythmicContrast: 0.4908677979838103
purpose: []
